### ISSUE TITLE
logger module raises exceptions on systems without /dev/log

### ISSUE THREAD

**Issue by jpwoodbu** [jpwoodbu/ari-backup#18]
I first saw this error when trying to run some of the tests within a docker container, which has no /dev/log file.

Running lvm_test.py, for example, produces output like this:
```
ERROR: testRunCustomWorkflow_updatesTopLevelSrcDirToSnapshotMountPointBasePath (__main__.RdiffLVMBackupTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lvm_test.py", line 375, in testRunCustomWorkflow_updatesTopLevelSrcDirToSnapshotMountPointBasePath
    command_runner=mock_command_runner)
  File "/usr/local/lib/python2.7/dist-packages/ari_backup/lvm.py", line 207, in __init__
    super(RdiffLVMBackup, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ari_backup/lvm.py", line 28, in __init__
    super(LVMSourceMixIn, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ari_backup/rdiff_backup_wrapper.py", line 61, in __init__
    super(RdiffBackup, self).__init__(label, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ari_backup/workflow.py", line 108, in __init__
    FLAGS.debug, FLAGS.stderr_logging)
  File "/usr/local/lib/python2.7/dist-packages/ari_backup/logger.py", line 43, in __init__
    syslog_handler = logging.handlers.SysLogHandler('/dev/log')
  File "/usr/lib/python2.7/logging/handlers.py", line 759, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 787, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
```

**Comment by rbarlow** [comment]
One solution to this might be to bind the /dev/log from the host into the container so that the host logger is available.

**Comment by jpwoodbu** [comment]
I wonder if there's a way to make the tests be more graceful when not having access to /dev/log. I don't want someone to create an off-the-shelf Ubuntu container in docker and have the tests fail.
